matrix:
  include:


    - language: python
      os: linux
      python: 3.7
      before_script:
        - cd python-bindings
        - bash install_rust.sh
        - export PATH=$PATH:$HOME/rust/bin:$HOME/.cargo/bin
        - pip install -r requirements-dev.txt
      script:
        - python setup.py install