matrix:
  include:
    - language: rust
      rust: stable
      os: linux
      script:
        - cargo build --manifest-path ./main/Cargo.toml --verbose
        - cargo test --manifest-path ./main/Cargo.toml

    - language: rust
      rust: beta
      os: linux
      script:
        - cargo build --manifest-path ./main/Cargo.toml --verbose
        - cargo test --manifest-path ./main/Cargo.toml

    - language: rust
      rust: nightly
      os: linux
      script:
        - cargo build --manifest-path ./python-bindings/Cargo.toml --verbose

    - language: python
      os: linux
      python: 3.7
      before_script:
        - cd python-bindings
        - bash install_rust.sh
        - pip install -r requirements-dev
      script:
        - python setup.py install