[package]
name = "rust_tokenizers"
version = "7.0.2"
authors = ["Guillaume Becquin <guillaume.becquin@gmail.com>"]
edition = "2018"
description = "High performance tokenizers for Rust"
repository = "https://github.com/guillaume-be/rust-tokenizers"
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
keywords = ["nlp", "machine-learning", "tokenizer"]

[dependencies]
csv = "1.1.6"
unicode-normalization = "0.1.22"
rayon = "1.5.3"
lazy_static = "1.4.0"
itertools = "0.10.5"
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.85"
regex = "1.6.0"
protobuf = "2.27.1"
hashbrown = "0.12.3"
unicode-normalization-alignments = "0.1.12"
thiserror = "1.0.35"

[dev-dependencies]
tempfile = "3.3.0"
dirs = "4.0.0"
reqwest = {version = "0.11.12", features = ["blocking"]}
anyhow = "1.0.65"

[build-dependencies]
protobuf-codegen-pure = {version = "2.27.1", optional = true}

[features]
proto-compile = [ "protobuf-codegen-pure" ]

[lib]
name = "rust_tokenizers"
path = "src/lib.rs"
crate-type = ["lib"]
